Repository cmelab/flowerMD, pull requests merged in 2023-11, with the labels that each got.

#93 `Graphene` now inherits from `Molecule`
  flowermd/base/molecule.py
  flowermd/library/surfaces.py
Labels: new module

#95 Add more descriptions to tutorials, update links to base code
  CONTRIBUTING.md
  tutorials/1-flowerMD-basics.ipynb
  tutorials/2-flowerMD-advanced.ipynb
Labels: Tutorials

#98 Update `README` and documentation with new installation instructions.
  .github/workflows/pytest.yml
  CONTRIBUTING.md
  README.md
  docs/source/installation.rst
  environment-dev.yml
  environment.yml
Labels: documentation

#96 Add surface wetting module
  docs/source/modules.rst
  docs/source/surface_wetting.rst
  flowermd/base/molecule.py
  flowermd/base/simulation.py
  flowermd/base/system.py
  flowermd/library/surfaces.py
  flowermd/modules/surface_wetting/__init__.py
  flowermd/modules/surface_wetting/surface_wetting.py
  flowermd/modules/surface_wetting/utils.py
  flowermd/modules/welding/__init__.py
  flowermd/modules/welding/utils.py
  flowermd/modules/welding/welding.py
  flowermd/tests/assets/graphene_snapshot.gsd
  flowermd/tests/assets/polyethylene_droplet.gsd
  flowermd/tests/assets/surface_wetting_ff.pkl
  flowermd/tests/assets/surface_wetting_init.gsd
  flowermd/tests/base/test_system.py
  flowermd/tests/base_test.py
  flowermd/tests/library/test_surfaces.py
  flowermd/tests/modules/test_surface_wetting.py
  flowermd/tests/modules/test_weld.py
  flowermd/tests/utils/test_actions.py
  paper/paper.md
  tutorials/5-flowerMD-surface-wetting.ipynb
  tutorials/data/polyethylene_droplet.gsd
Labels: new module
